apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS1uZXh1cy50cm9uZ252Lnh5eiI6eyJ1c2VybmFtZSI6ImRvY2tlci1yZXBvIiwicGFzc3dvcmQiOiIxMjNAMTIzYSIsImF1dGgiOiJaRzlqYTJWeUxYSmxjRzg2TVRJelFERXlNMkU9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-registry-creds
  namespace: app-dev
type: kubernetes.io/dockerconfigjson
